import { Stint_Ultra_Expanded } from 'next/font/google';
import './globals.css';

const stintUltraExpanded = Stint_Ultra_Expanded({
  variable: '--font-stint-ultra-expanded',
  weight: ['400'],
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${stintUltraExpanded.variable} antialiased text-text-primary`}>
        {children}
      </body>
    </html>
  );
}